export interface Identifiers {
  /**
   * The [Card Kingdom](https://www.cardkingdom.com/) etched card identifier.
   */
  cardKingdomEtchedId?: string;

  /**
   * The [Card Kingdom](https://www.cardkingdom.com/) foil card identifier.
   */
  cardKingdomFoilId?: string;

  /**
   * The [Card Kingdom](https://www.cardkingdom.com/) card identifier.
   */
  cardKingdomId?: string;

  /**
   * The [Card Market](https://www.cardmarket.com/en/Magic) card identifier.
   */
  mcmId?: string;

  /**
   * The [Card Market](https://www.cardmarket.com/en/Magic) card meta identifier.
   */
  mcmMetaId?: string;

  /**
   * The [Magic: The Gathering Arena](https://magic.wizards.com/en/mtgarena) card identifier.
   */
  mtgArenaId?: string;

  /**
   * The [Magic: The Gathering Online](https://magic.wizards.com/en/mtgo) card foil identifier.
   */
  mtgoFoilId?: string;

  /**
   * The [Magic: The Gathering Online](https://magic.wizards.com/en/mtgo) card identifier.
   */
  mtgoId?: string;

  /**
   * The universal unique identifier generated by MTGJSON. Each entry is unique. Entries are for MTGJSON v4 uuid generation.
   */
  mtgjsonV4Id?: string;

  /**
   * The [Wizards of the Coast](https://company.wizards.com/en) card identifier used in conjunction with [Gatherer](https://gatherer.wizards.com/Pages/Default.aspx).
   */
  multiverseId?: number;

  /**
   * The universal unique identifier generated by [Scryfall](https://scryfall.com/). Note that cards with multiple faces are not unique.
   */
  scryfallId?: string;

  /**
   * The unique identifier generated by [Scryfall](https://scryfall.com/) for this card's oracle identity. This value is consistent across reprinted card editions, and unique among different cards with the same name (tokens, Unstable variants, etc).
   */
  scryfallOracleId?: string;

  /**
   * The unique identifier generated by [Scryfall](https://scryfall.com/) for the card artwork that remains consistent across reprints. Newly spoiled cards may not have this field yet.
   */
  scryfallIllustrationId?: string;

  /**
   * The [TCGplayer](https://www.tcgplayer.com/) card identifier.
   */
  tcgplayerProductId?: string;

  /**
   * The [TCGplayer](https://www.tcgplayer.com/) etched card identifier.
   */
  tcgplayerEtchedProductId?: string;
}
