import { Identifiers } from "./Identifiers";
import { PurchaseUrls } from "./PurchaseUrls";

export interface SealedProduct {
  /**
   * A list of identifiers associated to a product.
   * @see Identifiers
   */
  identifiers: Identifiers;

  /**
   * The name of the product.
   */
  name: string;

  /**
   * Links that navigate to websites where the product can be purchased.
   * @see PurchaseUrls
   */
  purchaseUrls: PurchaseUrls;

  /**
   * The release date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format for the product.
   */
  releaseDate: string | null;

  /**
   * The universal unique identifier (v5) generated by MTGJSON. Each entry is unique.
   */
  uuid: string;
}
